spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kotlin_demo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    #    initialization-mode: always
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
